"""Default paths and environment variable names for configuration."""

from __future__ import annotations

from pathlib import Path

DEFAULT_CONFIG_DIR = Path.home() / ".config" / "allCode"
DEFAULT_CONFIG_PATH = DEFAULT_CONFIG_DIR / "config.yaml"
PROJECT_CONFIG_RELATIVE_PATH = Path(".allCode") / "config.yaml"
DEFAULT_STATE_DIR = Path.home() / ".allcode"
DEFAULT_GLOBAL_MEMORY_PATH = DEFAULT_STATE_DIR / "ALLCODE.md"
DEFAULT_SESSION_LOG_ROOT = DEFAULT_STATE_DIR / "session"

ENV_CONFIG_PATH = "ALLCODE_CONFIG"
ENV_MODEL = "ALLCODE_MODEL"
ENV_BASE_URL = "ALLCODE_BASE_URL"
ENV_API_KEY = "ALLCODE_API_KEY"
ENV_API_KEY_ENV = "ALLCODE_API_KEY_ENV"
ENV_WORKSPACE = "ALLCODE_WORKSPACE"
ENV_APPROVAL_MODE = "ALLCODE_APPROVAL_MODE"
ENV_WEB_SEARCH_URL = "ALLCODE_WEB_SEARCH_URL"
ENV_WEB_SEARCH_BACKEND = "ALLCODE_WEB_SEARCH_BACKEND"
ENV_WEB_SEARCH_API_KEY_ENV = "ALLCODE_WEB_SEARCH_API_KEY_ENV"
ENV_WEB_SEARCH_TIMEOUT = "ALLCODE_WEB_SEARCH_TIMEOUT"
ENV_WEB_SEARCH_LANGUAGE = "ALLCODE_WEB_SEARCH_LANGUAGE"
ENV_SOURCE_INTELLIGENCE = "ALLCODE_SOURCE_INTELLIGENCE"
ENV_LSP_ENABLED = "ALLCODE_LSP_ENABLED"
ENV_LSP_TIMEOUT_MS = "ALLCODE_LSP_TIMEOUT_MS"
