"""Default paths and environment variable names for configuration."""

from __future__ import annotations

from pathlib import Path

DEFAULT_CONFIG_DIR = Path.home() / ".config" / "allCode"
DEFAULT_CONFIG_PATH = DEFAULT_CONFIG_DIR / "config.yaml"
PROJECT_CONFIG_RELATIVE_PATH = Path(".allCode") / "config.yaml"

ENV_CONFIG_PATH = "ALLCODE_CONFIG"
ENV_MODEL = "ALLCODE_MODEL"
ENV_BASE_URL = "ALLCODE_BASE_URL"
ENV_API_KEY = "ALLCODE_API_KEY"
ENV_API_KEY_ENV = "ALLCODE_API_KEY_ENV"
ENV_WORKSPACE = "ALLCODE_WORKSPACE"
ENV_APPROVAL_MODE = "ALLCODE_APPROVAL_MODE"
ENV_WEB_SEARCH_URL = "ALLCODE_WEB_SEARCH_URL"
ENV_WEB_SEARCH_API_KEY_ENV = "ALLCODE_WEB_SEARCH_API_KEY_ENV"
ENV_WEB_SEARCH_TIMEOUT = "ALLCODE_WEB_SEARCH_TIMEOUT"
