"""Prompt constraint term dictionaries and command patterns."""

from __future__ import annotations

import re

READ_ONLY_TERMS = (
    "read-only",
    "read only",
    "do not edit",
    "don't edit",
    "no changes",
    "no file changes",
    "수정 금지",
    "변경 금지",
    "파일 변경 금지",
    "수정하지",
    "수정하지 마",
    "수정하지마",
    "변경하지",
    "파일 수정은 하지",
    "파일은 수정하지",
    "절대 수정",
    "읽기만",
    "분석만",
)

NO_SHELL_TERMS = (
    "no shell",
    "don't run commands",
    "do not run commands",
    "명령 실행 금지",
    "셸 실행 금지",
    "쉘 실행 금지",
)

NO_NETWORK_TERMS = (
    "no network",
    "offline",
    "검색 금지",
    "외부 검색 금지",
    "네트워크 금지",
)

STDLIB_ONLY_TERMS = (
    "standard library only",
    "stdlib only",
    "no third-party dependencies",
    "without third-party dependencies",
    "without external dependencies",
    "no external packages",
    "no dependencies",
    "built-in modules only",
    "표준 라이브러리만",
    "표준라이브러리만",
    "외부 패키지 없이",
    "외부 의존성 없이",
    "서드파티 없이",
    "의존성 없이",
)

VALIDATION_TERMS = (
    "pytest",
    "validate",
    "validation",
    "run tests",
    "run the tests",
    "테스트까지",
    "테스트",
    "tests",
    "test coverage",
    "테스트도",
    "테스트 추가",
    "테스트를 추가",
    "테스트 포함",
    "테스트 실행",
    "테스트를 실행",
    "검증",
    "재검증",
)

EXTERNAL_TERMS = (
    "latest",
    "current",
    "today",
    "search the web",
    "web search",
    "web evidence",
    "web source",
    "online source",
    "internet search",
    "look up",
    "공개 문서",
    "웹 검색",
    "웹검색",
    "웹 근거",
    "웹근거",
    "웹 자료",
    "웹자료",
    "인터넷 검색",
    "인터넷검색",
    "외부 검색",
    "외부검색",
    "최신",
    "현재",
    "오늘",
)

WORKSPACE_EVIDENCE_TERMS = (
    "actual file search",
    "search files",
    "find in files",
    "read the file",
    "실제 파일 검색",
    "파일 검색",
    "파일을 검색",
    "파일을 읽",
    "찾아줘",
    "검색으로 찾아",
    "directory structure",
    "file layout",
    "file list",
    "repo structure",
    "repository structure",
    "workspace structure",
    "디렉터리 구조",
    "디렉토리 구조",
    "파일 구조",
    "파일 목록",
    "저장소 구조",
    "워크스페이스 구조",
    "현재 디렉터리",
    "현재 디렉토리",
    "현재 폴더",
    "src 내",
    "src 안",
)

MUTATION_TERMS = (
    "implement",
    "create",
    "generate",
    "scaffold",
    "write",
    "add",
    "modify",
    "edit",
    "fix",
    "update",
    "refactor",
    "구현",
    "생성",
    "작성",
    "추가",
    "수정",
    "변경",
    "보강",
    "고쳐",
    "만들",
)

PROJECT_GENERATION_TERMS = (
    "new project",
    "create a project",
    "generate a project",
    "generate project",
    "project skeleton",
    "scaffold project",
    "bootstrap project",
    "새 프로젝트",
    "프로젝트 생성",
    "프로젝트 뼈대",
    "프로젝트를 만들어",
    "프로젝트를 만들",
    "프로젝트를 생성",
    "프로젝트를 구축",
    "프로젝트를 완성",
    "플랫폼 프로젝트",
    "애플리케이션 프로젝트",
)

MULTI_ARTIFACT_TERMS = (
    "cli",
    "entrypoint",
    "config",
    "configuration",
    "registry",
    "runner",
    "retry",
    "backoff",
    "logger",
    "logging",
    "jsonl",
    "audit",
    "plugin",
    "plugins",
    "commands",
    "modules",
    "tests",
    "pytest",
    "readme",
    "docs",
    "진입점",
    "설정",
    "레지스트리",
    "실행기",
    "재시도",
    "백오프",
    "로거",
    "로그",
    "감사",
    "플러그인",
    "명령",
    "모듈",
    "테스트",
    "문서",
)

PROJECT_OUTPUT_TERMS = (
    "project",
    "platform",
    "application",
    "app",
    "package",
    "service",
    "프로젝트",
    "플랫폼",
    "애플리케이션",
    "앱",
    "패키지",
    "서비스",
)

CODE_ARTIFACT_TERMS = (
    "code",
    "source",
    "script",
    "module",
    "package",
    "function",
    "class",
    "method",
    "api",
    "cli",
    "backend",
    "frontend",
    "library",
    "python",
    "javascript",
    "typescript",
    "코드",
    "소스",
    "스크립트",
    "모듈",
    "패키지",
    "함수",
    "클래스",
    "메서드",
    "메소드",
    "API",
    "CLI",
    "백엔드",
    "프론트엔드",
    "라이브러리",
)

UNSTABLE_KNOWLEDGE_TERMS = (
    "law",
    "legal",
    "regulation",
    "compliance",
    "price",
    "pricing",
    "cost",
    "market",
    "share",
    "benchmark",
    "kpi",
    "revenue",
    "roadmap",
    "budget",
    "forecast",
    "trend",
    "2025",
    "2026",
    "법률",
    "법적",
    "규정",
    "컴플라이언스",
    "가격",
    "비용",
    "시장",
    "점유율",
    "벤치마크",
    "실적",
    "매출",
    "로드맵",
    "예산",
    "전망",
    "동향",
    "지표",
)

ARGUMENTATION_FOLLOWUP_TERMS = (
    "counterargument",
    "rebuttal",
    "refute",
    "critique",
    "challenge the argument",
    "반박",
    "재반박",
    "반론",
    "비판",
    "논리를 만들",
    "논리를 제시",
    "주장을 검토",
)

FORMAT_FOLLOWUP_TERMS = (
    "summarize the conversation",
    "summarize our discussion",
    "turn this into",
    "rewrite as",
    "blog post",
    "article",
    "대화를 요약",
    "전체 대화",
    "요약해",
    "정리해",
    "형태로",
    "기고문",
    "블로그",
    "토론 수업용",
    "체크리스트로",
)

ANSWER_REFERENCE_TERMS = (
    "previous answer",
    "previous response",
    "last answer",
    "last response",
    "your answer",
    "앞 답변",
    "앞선 답변",
    "이전 답변",
    "방금 답변",
    "방금 제시",
    "앞서 제시",
    "방금 설명",
)

COMMON_WORKSPACE_DIRS = (
    "src",
    "lib",
    "app",
    "apps",
    "packages",
    "tests",
    "test",
    "docs",
    "examples",
)

ENGLISH_CHANGE_COMMAND = re.compile(
    r"^\s*(?:please\s+)?"
    r"(?:implement|create|modify|edit|write|fix|add|update|delete|generate|scaffold|refactor|change)\b"
    r"|(?:can|could|would)\s+you\s+"
    r"(?:implement|create|modify|edit|write|fix|add|update|delete|generate|scaffold|refactor|change)\b",
    re.IGNORECASE,
)
KOREAN_CHANGE_COMMAND = re.compile(
    r"(?:구현|생성|수정|변경|추가|작성|삭제|보강|고쳐|만들)(?:해\s*줘|해줘|해주세요|하라|해라|하시오|하자|어\s*줘|어줘|줘)"
)
KOREAN_CHANGE_CONNECTIVE = re.compile(
    r"(?:구현|생성|수정|변경|추가|작성|삭제|보강|고쳐|만들)(?:하고|해서|하여)"
)
